services:
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root

  app:
    container_name: app
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
      - /app/node_modules
    networks:
      - app-network
    depends_on:
      - mysql

  nginx-fc:
    container_name: nginx-fc
    image: nginx:stable-alpine-slim
    networks:
      - app-network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/app.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    depends_on:
      - app

volumes:
  mysql_data:
    driver: local

networks:
  app-network:
    driver: bridge
